### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by Hyzbade** [samthiriot/genlab#44]
I think there is a problem, I'll explain later

**Comment by Hyzbade** [comment]
When I'm running TNK (for example), I obtain this line (among others) in the CSV file:
"2;genome 1;-2147483.0;1.1507200087329537;2147484.1507200086;-2147483.0;0.4279567157897277;2147483.4279567157;0.2720588009919122;0.709353861603006"

It means:
X gene = 0.2720588009919122
Y gene = 0.709353861603006
F1 = 0.4279567157897277
F2 = 1.1507200087329537

But, this test problem is defined by:
F1 = x
F2 = y

**Comment by Hyzbade** [comment]
Problem above the export:
ID 375523436, GENES [0.10854840589549052, 0.9869175015274971], VALUES [0.9869175015274971, 0.10854840589549052], TARGETS [0.0, 0.0], FITNESS [0.9869175013093825, 0.10854840609643068]
In this output, F1 = y and F2 = x

**Comment by Hyzbade** [comment]
After each fast non dominate sort, there is a trace. In this example, between iteration 37 and iteration 38, some individuals change their genes values.
This is random.

I=37
ID 1853823574, GENES [1.0435039376925606, 0.04968531330263259], VALUES [1.0435039376925606, 0.04968531330263259], TARGETS [0.0, 0.0], FITNESS [1.0435039377973898, 0.04968531338949004]

I=38
ID 1853823574, GENES [0.947035045143262, 0.037863452748355536], VALUES [1.0435039376925606, 0.04968531330263259], TARGETS [0.0, 0.0], FITNESS [1.0435039377973898, 0.04968531338949004]

**Comment by samthiriot** [comment]
Many questions there, I don't achieve to follow everything... 

for the first problem (original post of the bug), you note "FIXED": is it fixed ?  

I'll assume the other ones are other bugs you identify as related. 

About  this line:
> ID 375523436, GENES [0.10854840589549052, 0.9869175015274971], VALUES [0.9869175015274971, 0.10854840589549052], TARGETS [0.0, 0.0], FITNESS [0.9869175013093825, 0.10854840609643068]
> In this output, F1 = y and F2 = x
It is not wrong: the genes and values are just not in the same order. The order of genes and goals might be different at display. Genes are in the order of genes in the genome, while values/target/fitness are in the order of goal algorithms in the NSGA2 algorithm. Both these orders are constant in time; but in general there is nothing such as a natural correspondance between Fx and x,y . 

BTW, I commited today a fix on the display of individuals and on the storage of fitness/values: the implementation was obviously faulty (the size of target/fitness in individuals is not the size of the genes). In practice the individual cannot initialize itself these arrays, as he has no clue on the order nor count of targets. So these elements are not final anymore and are only defined when receiving the values (in receiveComputationStateChange in GeneticAlgoOneGenerationExec). 

For the last message: it's true, a final something in java will never change. But if the object is mutable, what will never change is the reference. So in 
> final Object[] results
you can only do once in the constructor
> results = new Object[12]
any other one would not even be accepted at compilation. 
But you can still do
> results[1] = 12.3
The reference is the same, but the content changes. 

So maybe you reuse the same individual between two iterations. In this case, as the fitness is now stored inside the individual, you do replace its previous fitness by the new one. If you don't want this behavior, you have to clone you individual before sending it for another evaluation.

**Comment by Hyzbade** [comment]
I think I've fixed the problem. When we create the offspring, sometimes we just copy the parents. This copy was made by this line:

> offspring.add(new AnIndividual(p1)); // p1 is one parent

And here the constructors:

> public AnIndividual(AGenome genome, Object[] genes) {
	super();
	this.id = lastId++;
	this.genome = genome;
	this.genes = genes;
	this.fitness = null;
	this.targets = null;
	this.values = null;
	this.rank = Integer.MAX_VALUE;
	this.crowdedDistance = -1d;
}

> public AnIndividual(AnIndividual ind) {
	this(ind.genome, ind.genes);
}

Since we sent ind.genes (which is not a copy), I strongly assume that in case of mutation of the child afterwards, the mutation affects the reference!
