### ISSUE TITLE
(graphiti) Dare you to remove a wrap component?

### ISSUE THREAD

**Issue by Hyzbade** [samthiriot/genlab#60]
If you remove a wrap component, i.e. NSGA-II, but you didn't want to. Since we can't currently undo our actions, we just have to close the tab without save the project. When you apply this tip and you open back the project, we cannot edit the wrap component neither its content.

**Comment by Hyzbade** [comment]
1094238 [glConsumeMessages] WARN genlab.gui.graphiti.genlab2graphiti.GenLabIndependenceSolver  - Fri Jun 19 15:05:06 CEST 2015 - unable to find mapping for key genlab.workflow./local00/home/H01376/Documents/workspaces/runtime-genlab.product/examples.watts-strogatz-nsga2.algos.genlab.algog.algos.meta.GoalAlgo
1094287 [glConsumeMessages] WARN genlab.gui.graphiti.genlab2graphiti.GenLabIndependenceSolver  - Fri Jun 19 15:05:06 CEST 2015 - unable to find mapping for key genlab.workflow./local00/home/H01376/Documents/workspaces/runtime-genlab.product/examples.watts-strogatz-nsga2.algos.genlab.algog.algos.meta.NSGA2GeneticExplorationAlgo
1094287 [glConsumeMessages] WARN genlab.gui.graphiti.diagram.GraphitiFeatureProvider  - Fri Jun 19 15:05:06 CEST 2015 - cannot provide a feature for a wrong object: null
1094287 [glConsumeMessages] WARN genlab.gui.graphiti.diagram.GraphitiFeatureProvider  - Fri Jun 19 15:05:06 CEST 2015 - cannot provide a feature to delete this object: null
[org.eclipse.graphiti.mm.pictograms.impl.DiagramImpl@2db61b13 (visible: true, active: false) (gridUnit: 10, diagramTypeId: genlab.graphiti.diagtypes.workflow, name: watts-strogatz-nsga2, snapToGrid: true, showGuides: false, verticalGridUnit: -1, version: 0.10.0)]

**Comment by samthiriot** [comment]
Makes sense, as this tip is creating an inconsistent step: the alto was removed from the workflow but not from the graphical counterpart. I'm afraid your trick is to avoid. The actual solution would be to implement cancellation, buts its tedious compared to the actual users !
